//go:build !ierr

// Code generated by github.com/shynome/err4 DO NOT EDIT

package main

import (
	"errors"
)

func main() {
	var ierr error
	var ierr2 error
	_, _ = ierr, ierr2

	ierr = errors.New("e")
	if ierr != nil {
		return
	}

	var e1, e2 error
	_, ierr, ierr2 = 7, e1, e2
	if ierr != nil || ierr2 != nil {
		return
	}
}

func fn() (ierr error) {
	ierr = errors.New("e")
	if ierr != nil {
		return
	}
	return
}

func fn2() (ierr error) {
	ierr = errors.New("e")
	if ierr != nil {
		return
	}
	return
}
